services:
  web:
    build:
      context: . 
      dockerfile: php/Dockerfile
    ports:
      - "9000:80"
    depends_on:
      - db
      - api
  db:
    build: ./sql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  api:
    build: ./api
    ports:
      - "8080:80"