FROM php:8.5-apache
RUN a2enmod rewrite
RUN a2enmod mime
COPY php/000-default.conf /etc/apache2/sites-available/000-default.conf
RUN a2ensite 000-default.conf
RUN docker-php-ext-install pdo pdo_mysql
RUN a2enconf mime-fix
COPY front/ /var/www/html/
EXPOSE 80
